import unittest
from unittest.mock import MagicMock, patch
from langchain_core.messages import AIMessage, HumanMessage
from agent import run_research, agent, route_search, ResearchState


class TestResearchBot(unittest.TestCase):

    @patch("agent.ChatGoogleGenerativeAI")
    @patch("agent.TavilySearch")
    def test_run_research_no_search(self, mock_tavily, mock_llm_class):
        # Setup mock LLM response for greeting (NO_SEARCH)
        mock_llm_instance = MagicMock()
        mock_llm_class.return_value = mock_llm_instance
        
        # We need two responses: one for generate_query, one for respond_directly
        mock_llm_instance.invoke.side_effect = [
            AIMessage(content="NO_SEARCH"),
            AIMessage(content="Hello! How can I help you today?")
        ]

        messages = [{"role": "user", "content": "Hi there!"}]
        report = run_research(messages)

        # Verify that TavilySearch was NOT invoked
        mock_tavily.assert_not_called()
        self.assertEqual(report, "Hello! How can I help you today?")

    @patch("agent.ChatGoogleGenerativeAI")
    @patch("agent.TavilySearch")
    def test_run_research_with_search(self, mock_tavily_class, mock_llm_class):
        # Setup mock LLM and Tavily responses
        mock_llm_instance = MagicMock()
        mock_llm_class.return_value = mock_llm_instance
        
        # Responses: one for query generation, one for synthesize_report
        mock_llm_instance.invoke.side_effect = [
            AIMessage(content="latest developments in quantum computing"),
            AIMessage(content="This is the synthesized report about quantum computing.")
        ]

        mock_tavily_instance = MagicMock()
        mock_tavily_class.return_value = mock_tavily_instance
        mock_tavily_instance.invoke.return_value = [
            {"url": "http://example.com", "title": "Quantum", "content": "Quantum advances in 2026"}
        ]

        messages = [{"role": "user", "content": "Tell me about quantum computing developments."}]
        report = run_research(messages)

        # Verify TavilySearch was invoked with the query generated by LLM
        mock_tavily_instance.invoke.assert_called_once_with("latest developments in quantum computing")
        self.assertIn("synthesized report", report)

    def test_route_search(self):
        # Test routing function behavior
        state_no_search = {"query": "NO_SEARCH", "messages": [], "search_results": [], "report": ""}
        state_search = {"query": "quantum computing", "messages": [], "search_results": [], "report": ""}

        self.assertEqual(route_search(state_no_search), "respond_directly")
        self.assertEqual(route_search(state_search), "search")


if __name__ == "__main__":
    unittest.main()
